# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxBgWSEqWe63cglskQJJE8RudhMEgrYg
"""
import torch
from torch.utils.data import DataLoader, TensorDataset
def k_cross_data_split(sample_data, mask, batch_size,fold,kf):
  foldsize=sample_data.shape[0]//kf
  train_image=torch.zeros([1,3,256,512]).type(torch.float)
  train_mask=torch.zeros([1,1,256,512]).type(torch.float)
  for j in range(kf):
    if fold!=j:
      if j!=kf-1:
        train_image=torch.cat((train_image,sample_data[j*foldsize:(j+1)*foldsize,:,:,:]),0)
        train_mask=torch.cat((train_mask,mask[j*foldsize:(j+1)*foldsize,:,:,:]),0)
      else:
        train_image=torch.cat((train_image,sample_data[j*foldsize:,:,:,:]),0)
        train_mask=torch.cat((train_mask,mask[j*foldsize:,:,:,:]),0)
  if fold!=kf-1:
    test_image=sample_data[fold*foldsize:(fold+1)*foldsize,:,:,:]
    test_mask=mask[fold*foldsize:(fold+1)*foldsize,:,:,:]
  else:
    test_image=sample_data[fold*foldsize:,:,:,:]
    test_mask=mask[fold*foldsize:,:,:,:]
  train_data=TensorDataset(train_image[1:,:,:,:], train_mask[1:,:,:,:])
  test_data=TensorDataset(test_image[1:,:,:,:], test_mask[1:,:,:,:])
  return train_data, test_data


def cross_val(kf,sample_data,mask_data,model,para):
  for i in range(kf):
    if para['resume']>i:
      continue   
    train_data, test_data= k_cross_data_split(sample_data, mask_data, para['batch_size'],i,kf)
    train_loader=DataLoader(dataset=train_data, batch_size=para['batch_size'], shuffle=True,drop_last=True)
    test_loader=DataLoader(dataset=test_data, batch_size=para['batch_size'], shuffle=False,drop_last=True)
    print('fold:',i)
    model1=model.to(device)
    model_train(model1,train_loader,test_loader,para,i)
  return
